dist: bionic
language: python

python:
  - "3.8"

addons:
  chrome: stable

branches:
  only:
    - staging

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers --path webdrivers

env:
  global:
    - SECRET_KEY=azertyuiopqsdfghjklmwxcvbn
    - DB_NAME=travis_ci_test
    - DB_USER=travis
    - DB_PASSWORD=
    - DB_HOST=127.0.0.1
    - DB_PORT=5432

services:
  - postgresql

script:
  - python manage.py test -v
