addons:
  chrome: stable
language: python
python:
  - "3.9"

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - SECRET_KEY="azertyuiopqsdfghjklmwxcvbn"
    - DB_NAME="travis_ci_test"
    - DB_USER="travis"
    - DB_PASSWORD=""
    - DB_HOST="127.0.0.1"
    - DB_PORT="5432"

services:
  - postgresql

script:
  - ./manage.py test
