addons:
  chrome: stable
language: python
python:
  - "3.8"
  - "3.9"

before_script:
  - echo $PATH
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres
  - wget http://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8/bin/
  - export CHROME_BIN=chromium-browser

env:
  global:
    - SECRET_KEY=azertyuiopqsdfghjklmwxcvbn
    - DB_NAME=travis_ci_test
    - DB_USER=travis
    - DB_PASSWORD=
    - DB_HOST=127.0.0.1
    - DB_PORT=5432

services:
  - postgresql

script:
  - ./manage.py test
