addons:
  chrome: stable
language: python
python:
  - "3.9"

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - install-webdrivers --path webdrivers

env:
  global:
    - SECRET_KEY=azertyuiopqsdfghjklmwxcvbn
    - DB_NAME=travis_ci_test
    - DB_USER=travis
    - DB_PASSWORD=
    - DB_HOST=127.0.0.1
    - DB_PORT=5432

services:
  - postgresql

script:
  - python manage.py test -v
