dist: bionic
language: python

python:
  - "3.8"

addons:
  chrome: stable

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers --path webdrivers

services:
  - postgresql

script:
  - python manage.py test
